[tool.mypy]
namespace_packages = true
strict = true
explicit_package_bases = true
mypy_path = "src/python"
exclude = '''(?x)(
    ^BUILD$
    | ^conftest\.py$
    | _test\.py$"
)'''

no_implicit_optional = true
implicit_reexport = false
local_partial_types = true

warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true

# Error output
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true
pretty = true
color_output = true
error_summary = true
